# Example with Erbium

## Call libraries

In [1]:
import numpy as np
import scipy as sp
import scipy.optimize as opt

# Function

In [2]:
def S_cal(u,b):
    def U_t_b(uu,bb):
        return np.matmul(np.transpose(uu),bb)
    def U_U_t(uu):
        return np.matmul(np.transpose(uu),uu)
    def omega(uu,bb):
        return np.matmul(np.linalg.pinv(U_U_t(uu)),U_t_b(uu,bb))
    return np.transpose(np.matmul(np.transpose(omega(u,b)),np.transpose(u)))

In [3]:
def Omega_Matrix(u,b):
    def U_t_b(uu,bb):
        return np.matmul(np.transpose(uu),bb)
    def U_U_t(uu):
        return np.matmul(np.transpose(uu),uu)
    return np.matmul(np.linalg.pinv(U_U_t(u)),U_t_b(u,b))

In [4]:
def S_the(omega,u):
    return np.matmul(u,omega)

In [5]:
U2 = np.vstack(np.array([0.0195,
                         0.0282,
                         0,
                         0,
                         0,
                         0.7125,
                         0,
                         #0,
                         #0,
                         #0,
                         #0.9183
]))
U4 = np.vstack(np.array([0.1173,
                         0.0003,
                         0.1733,
                         0.5354,
                         0,
                         0.4125,
                         0.1469,
                         #0,
                         #0,
                         #0.0189,
                         #0.5262
]))
U6 = np.vstack(np.array([1.4316,
                         0.3953,
                         0.0099,
                         0.461,
                         0.2211,
                         0.0925,
                         0.6266,
                         #0.2232,
                         #0.1272,
                         #0.2256,
                         #0.1172
]))

In [6]:
U = np.hstack((U2,U4,U6))

In [7]:
S_exp = np.vstack(np.array([1.972,
                        
                        
                        0.554,
                        1.125,
                        3.029,
                        0.180,
                        9.474,
                        1.111
]))

## Test 1

In [8]:
print(U)
print(S_exp)

[[  1.95000000e-02   1.17300000e-01   1.43160000e+00]
 [  2.82000000e-02   3.00000000e-04   3.95300000e-01]
 [  0.00000000e+00   1.73300000e-01   9.90000000e-03]
 [  0.00000000e+00   5.35400000e-01   4.61000000e-01]
 [  0.00000000e+00   0.00000000e+00   2.21100000e-01]
 [  7.12500000e-01   4.12500000e-01   9.25000000e-02]
 [  0.00000000e+00   1.46900000e-01   6.26600000e-01]]
[[ 1.972]
 [ 0.554]
 [ 1.125]
 [ 3.029]
 [ 0.18 ]
 [ 9.474]
 [ 1.111]]


In [9]:
Omega_Matrix(U,S_exp)
S_cal(U,S_exp)
print(Omega_Matrix(U,S_exp))

[[ 10.2402257 ]
 [  5.10966431]
 [  0.76457002]]


In [10]:
def chi_squa(omega,U,S_exp):
    return np.sum(np.subtract(S_the(omega,U),S_exp)**2/(len(S_exp-3)))
print(chi_squa(Omega_Matrix(U,S_exp),U,S_exp))

0.0113043652446


In [11]:
def RMS(omega,U,S_exp):
    return chi_squa(omega,U,S_exp)**(1/2)
print(RMS(Omega_Matrix(U,S_exp),U,S_exp))

0.106321988528


In [12]:
def S_err(omega,U,S_exp):
    return RMS(omega,U,S_exp)*np.diag(U)
print(S_err(Omega_Matrix(U,S_exp),U,S_exp))

[  2.07327878e-03   3.18965966e-05   1.05258769e-03]


## with Scipy

In [13]:
def diff(omega,U,S_exp):
    return np.sum(np.subtract(S_the(omega,U),S_exp))
diff(Omega_Matrix(U,S_exp),U,S_exp)

-0.10424086452155282

In [14]:
opt.least_squares(diff,[10,5,0.5],args=(U,S_exp),ftol=1e-15,gtol=1e-15,xtol=1e-15).x

array([ 10.07585773,   5.13827421,   0.82310882])

In [15]:
def chi_squared(diff, U, S_exp):
    return 

Working with pandas

In [16]:
sample=np.array([[i*np.random.random_sample() for i in np.array([1.972,0.554,1.125,3.029,0.180,9.474,1.111])] for j in range(20)])

In [17]:
import pandas as pd

In [18]:
sample=pd.DataFrame(data=sample[0:,0:],columns=["i","S1","S2","S3","S4","S5","S6"])